.TH CAMMILL 1
.SH NAME
cammill \- DXF to G-Code CAM-Tool
.SH SYNOPSIS
.B cammill
.SH DESCRIPTION
This manual page documents briefly the
.B cammill
command.
.PP
.B cammill
CAM-Tool

.I cammill 
needs a running X11 session and Open-GL support.

.SH OPTIONS
.TP
.B # cammill test.dxf
.SH AUTHOR
.B cammill
was written by Oliver Dippel <oliver@multixmedia.org>.
.PP
This manual page was written by Oliver Dippel <oliver@multixmedia.org>
